defaults:
  - _self_
  - model/encoder: w2v2
  - model/frontend: ffnn
  - model/personalization/enrollment: none
  - model/personalization/fusion: attention
  - data: aibo
meta:
  results_root: ???
  device: cpu
hparams:
  epochs: 50
  optimizer: Adam
  lr: 0.0001
  bs: 4